# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_list_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=0),
        ),
    ]
