# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171006_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lists', to='app.User'),
        ),
    ]
